remotestorage/remotestorage-widget

- src/assets/styles.css
- src/assets/widget.html
Fixes #20 
I just had to move the margins for the big headline of the first view ("Own Your Data") to also be used for the "Connect your storage" headline.
I also noticed that when all 3 backends are enabled, the button for the last backend (Google Drive) is cut off at the bottom (see screenshot). I increased the overall max-height by 10 pixels to fix that.
> Fix styles

- src/widget.js
closes #30 
This also fixes a bug where a wrong comparison check lead to always showing the backend chooser screen, even when there is no other backend than remoteStorage.
And when clicking the icon in initial state, it behaves the same as when clicking the widget's content, instead of doing nothing at all.
> Never close widget when not connected

- src/assets/styles.css
Its height was set to make the animation look smooth (84ca7ac5), but on
macOS the line height is not enough for some gliphs
Fixes #34
> Increase the height of the user id line

- src/assets/styles.css
Refs #39 
Probably not the best solution, but at least it keeps the buttons around :)
> Truncate too long user addresses with ellipsis

- src/widget.js
Closes #23 
This closes the widget after the sync is done with an additional delay of 1.5 seconds.
> Auto-close on load (after first sync)

- src/assets/styles.css
The icon is floating left, but switching to not be floating in the open dialogs, while the initial box only transitions to its zero height for the default transition duration.
fixes #44
> Fix content jumping around

- src/widget.js
Instead of showing an error message when the user denies access during the OAuth dance, the widget just goes back to the initial state.
This needs the changes from remotestorage/remotestorage.js#1018 to work, as it adds the custom `code` property to the error.
> Reset to initial state when getting an access denied error

- README.md
- src/widget.js
`openWidget()` -> `open()`
`closeWidget()` -> `close()`
`toggleWidget()` -> `toggle()`
> Rename functions and document them in Readme

- README.md
- demo/index.html
- src/widget.js
I thought the release version of the widget shouldn't pollute the console so much, so I made the logging configurable.
For the demo it's still enabled.
> Make logging configurable, disable by default

- src/assets/styles.css
* Set the box-sizing of `rs-widget` to the same all the enclosed elements and ajust its closed `max-width` accordingly.
* Improve sorting of `rs-widget` properties
> Fix box-sizing not set explicitly on rs-widget

- src/assets/styles.css
Without this, it uses the rs-widget main div's max-width, which is
400px on small screens.
> Add width for closed state

- src/assets/styles.css
- src/assets/widget.html
Fixes #67
This fixes the pill-shaped button in mobile Safari.
I also disabled the auto-capitalization of the first letter for the storage address input field.
> Fix button shape in mobile Safari

- src/assets/styles.css
Fixes #39
This way, the buttons will never be pushed out of view, and the content just uses the remaining space.
> Use flexbox for better arrangement of content and buttons

- src/widget.js
This happens e.g. when loading an app while offline.
> Don't try to call `getTime()` on null

- demo/index.html
- src/widget.js
This adds a new option for app developers, so they can hide the initial connect hint and instead show the sign-in (or choose-backend) dialog directly.
This is useful when you just want to integrate the sign-in dialog from the widget (with the errors and all), but not much else. You can try it in action with Inspektor right now (also includes the code from #78):
https://inspektor.5apps.com/
> Add config option for skipping the initial state

- src/widget.js
When using the normal UI for disconnecting one has to open the widget to click the button. However, when using custom UI to trigger the disconnect, and the widget is in closed state, it won't open and then get into a slightly broken in-between state.
This ensures the widget is always opened on disconnect. Not sure if it's the best place to put the open() call though.
fixes #77
replaces #78
> Ensure widget is opened on disconnect

- bower.json
- package.json
- scripts/update-bower-version.sh
We need this merged before we can register the package ([see the docs](https://bower.io/docs/creating-packages/#register)). I have tried this locally (`bower install /path/to/your/remotestorage-widget --save`.
Fixes #82
> Create bower package

- src/assets/styles.css
- src/assets/widget.html
- src/widget.js
Disables the connect button both visually and functionally upon pressing it, until either a discovery error appears, or it redirects to the storage provider's OAuth dialog.
connected to #26
> Disable connect button when connecting

- src/assets/styles.css
- src/assets/widget.html
- src/widget.js
Right now elements are only hidden by setting the opacity to 0, which does not actually
hide them from screen readers.
This PR also sets the the `aria-hidden` attribute.
A demo of this version of the widget can be found at https://rs-widget-demo.5apps.com/.
> Improve accessibility by marking hidden elements appropriately

- src/assets/styles.css
There's an additional, unintentional margin of about 2 pixels under the icons of the small action buttons.
This improves the layout, so that the icon is set perfectly in the vertical center, and the buttons also make better use of the available space in general.
Before:
After:
> Optimize layout of small buttons

- src/widget.js
Continuation of #93.
This focuses the address input field when selecting the RS option during sign-in.
The difference between this and @rosano's PR is that it does not focus the input when the widget opens the sign-in form immediately (without the options), because we don't want to mess with whatever other focus operations may be going on at rendering time, in the app that the widget is embedded in.
> Focus address input on sign-in

- src/widget.js
This changes the widget byline text to "Synchronizing" during syncs that take longer than 1 second. The 1-second limit prevents the text from changing for only a split second during normal folder checks, which complete very quickly, even on slow connections.
The limit doesn't apply when clicking the sync button, so you get instant feedback in that case.
closes #88
> Change byline during sync

- src/assets/circle-open.svg
- src/assets/styles.css
- src/assets/widget.html
- src/widget.js
This makes it much clearer that something is actually happening, while you're waiting for the Webfinger request to resolve and the subsequent OAuth redirect to change the page.
> Change button text and add spinner when connecting

- src/assets/styles.css
I would guess I added that `position: fixed` in order to have the widget float on top with the backdrop over the page, while the rest could be scrolled in theory. In any case, it broke the layout when putting the widget in other positions, like e.g. centered, or on the page bottom.
fixes #106
> Fix alternative positioning

- src/assets/styles.css
- src/assets/widget.html
- src/widget.js
Place the modal backdrop element inside the widget container, so that even if the widget is attached to positioned elements, the modal backdrop does not display over the widget contents.
I think this approach is better to fix the problem as it does not require the developers to apply any hacks.
I should note that i don't have much experience with styling, so i don't know if placing the backdrop inside the widget can cause other display issues that i can't think of.
Fixes #109
Fixes #110
> Fix modal backdrop display

- src/assets/styles.css
Hello ; I keep getting those pesky CSS warnings:
- Selector expected.  Ruleset ignored due to bad selector.
- Error in parsing value for 'display'.  Declaration dropped. (x2)
So I removed a trailing comma, and changed "normal" (which is not a valid attr. for `display`) to "block" (the default value).
Cheers ; PS RemoteStorage is fantastic, thanks a **lot**.
> Fix wrong display attribute values in CSS

- src/widget.js
Use new sync status information from rs.js to only show sync as finished, when it was actually completed. Otherwise, wait for next sync and mark completed as reported as such.
Requires https://github.com/remotestorage/remotestorage.js/pull/1290
> Improve sync status display/behavior
